export const WATCHLIST_STOCKS = {
  PSO: {
    name: "Pakistan State Oil",
    sector: "Energy",
    price: 467,
    prevClose: 459,
    weekHigh52: 506.75,
    weekLow52: 300,
    pe: 8.2,
    marketCap: "245B",
    volume: "3.2M",
    analystRating: "Strong Buy",
    analystCount: 7,
    targetPrice: 646,
    dividendYield: 3.1,
    beta: 1.22,
    eps: 56.9,
    roe: 18.5,
    debtToEquity: 1.8,
    shariah: false,
    description: "Dominant oil marketing company, ~50% market share",
    catalysts: ["Circular debt resolution", "Earnings momentum (+154% QoQ)", "All analysts Strong Buy"],
    risks: ["Thin EBITDA margins (~1.6%)", "Govt fuel pricing caps", "Circular debt timeline uncertain"],
    priceHistory: [300, 320, 345, 360, 380, 395, 420, 445, 470, 506, 490, 467],
    volumeHistory: [2.1, 2.5, 3.0, 2.8, 3.5, 4.2, 3.8, 3.1, 3.6, 4.8, 3.9, 3.2],
    months: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    newsKeywords: ["oil prices", "circular debt pakistan", "PSO earnings", "fuel pricing pakistan", "energy crisis"],
  },
  MEBL: {
    name: "Meezan Bank",
    sector: "Islamic Banking",
    price: 488,
    prevClose: 482,
    weekHigh52: 505,
    weekLow52: 238,
    pe: 11.5,
    marketCap: "884B",
    volume: "2.8M",
    analystRating: "Buy",
    analystCount: 5,
    targetPrice: 672,
    dividendYield: 2.1,
    beta: 0.89,
    eps: 42.4,
    roe: 24.2,
    debtToEquity: 0,
    shariah: true,
    description: "Pakistan's largest Islamic bank — structural moat",
    catalysts: ["Islamic finance tailwind", "Low beta / defensive", "Analyst target Rs.672"],
    risks: ["Valuation premium to peers", "Earnings date delayed to April", "Regulatory shifts"],
    priceHistory: [238, 265, 290, 310, 340, 370, 400, 430, 460, 505, 495, 488],
    volumeHistory: [1.8, 2.2, 2.5, 2.3, 2.9, 3.1, 2.7, 2.4, 3.0, 3.8, 3.2, 2.8],
    months: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    newsKeywords: ["islamic banking pakistan", "meezan bank", "SBP policy rate", "islamic finance"],
  },
  UBL: {
    name: "United Bank Limited",
    sector: "Banking",
    price: 460,
    prevClose: 455,
    weekHigh52: 517,
    weekLow52: 188,
    pe: 6.08,
    marketCap: "1.24T",
    volume: "4.1M",
    analystRating: "Strong Buy",
    analystCount: 3,
    targetPrice: 590,
    dividendYield: 3.5,
    beta: 1.49,
    eps: 50.62,
    roe: 22.8,
    debtToEquity: 0,
    shariah: false,
    description: "Lowest P/E among major banks, Middle East franchise",
    catalysts: ["P/E of 6x — deeply undervalued", "160% interim dividend payout", "Middle East diversification"],
    risks: ["Rate cuts compress margins", "High beta (1.49)", "Pulled back from ATH"],
    priceHistory: [188, 220, 260, 290, 330, 370, 400, 430, 460, 517, 480, 460],
    volumeHistory: [3.0, 3.5, 4.0, 3.8, 4.5, 5.2, 4.8, 4.1, 4.6, 5.8, 4.9, 4.1],
    months: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    newsKeywords: ["UBL earnings", "pakistan banking sector", "SBP interest rate", "UBL dividend"],
  },
  SYS: {
    name: "Systems Limited",
    sector: "Technology",
    price: 520,
    prevClose: 512,
    weekHigh52: 580,
    weekLow52: 310,
    pe: 22.5,
    marketCap: "120B",
    volume: "1.5M",
    analystRating: "Buy",
    analystCount: 4,
    targetPrice: 680,
    dividendYield: 0.8,
    beta: 1.15,
    eps: 23.1,
    roe: 19.5,
    debtToEquity: 0.3,
    shariah: true,
    description: "Premier IT exporter — USD revenue hedge",
    catalysts: ["USD revenues — natural FX hedge", "IT exports growing 20%+ YoY", "AI/digital transformation demand"],
    risks: ["High P/E vs PSX average", "Brain drain / talent retention", "Client geopolitical concerns"],
    priceHistory: [310, 340, 360, 380, 410, 440, 470, 500, 540, 580, 545, 520],
    volumeHistory: [1.0, 1.2, 1.4, 1.3, 1.6, 1.8, 1.5, 1.3, 1.7, 2.2, 1.8, 1.5],
    months: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    newsKeywords: ["pakistan IT exports", "systems limited", "PKR USD exchange", "tech outsourcing pakistan"],
  },
  LUCK: {
    name: "Lucky Cement",
    sector: "Cement",
    price: 490,
    prevClose: 485,
    weekHigh52: 550,
    weekLow52: 320,
    pe: 12.8,
    marketCap: "158B",
    volume: "1.8M",
    analystRating: "Buy",
    analystCount: 5,
    targetPrice: 600,
    dividendYield: 0.84,
    beta: 1.05,
    eps: 38.3,
    roe: 16.2,
    debtToEquity: 0.5,
    shariah: true,
    description: "Diversified conglomerate — cement + chemicals + power",
    catalysts: ["Infrastructure/CPEC spending", "Export markets (Afghanistan/Iraq)", "Consistent QoQ earnings growth"],
    risks: ["Cement overcapacity", "Low dividend yield", "Regional export geopolitical risk"],
    priceHistory: [320, 340, 360, 380, 400, 420, 445, 470, 500, 550, 510, 490],
    volumeHistory: [1.4, 1.6, 1.8, 1.7, 2.0, 2.3, 2.1, 1.8, 2.2, 2.9, 2.4, 1.8],
    months: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    newsKeywords: ["CPEC infrastructure", "cement sector pakistan", "lucky cement", "construction pakistan"],
  },
  PPL: {
    name: "Pakistan Petroleum",
    sector: "Energy",
    price: 262,
    prevClose: 258,
    weekHigh52: 284.60,
    weekLow52: 135,
    pe: 7.5,
    marketCap: "643B",
    volume: "2.5M",
    analystRating: "Buy",
    analystCount: 4,
    targetPrice: 386,
    dividendYield: 4.2,
    beta: 1.45,
    eps: 34.9,
    roe: 14.8,
    debtToEquity: 0.2,
    shariah: true,
    description: "2nd largest gas producer — strategic energy asset",
    catalysts: ["Domestic energy security play", "Technical targets Rs.290-386", "Strong support at Rs.255-265"],
    risks: ["High beta (1.45) & volatility", "Circular debt systemic risk", "Govt pricing controls"],
    priceHistory: [135, 155, 170, 185, 200, 215, 235, 250, 265, 284, 270, 262],
    volumeHistory: [1.8, 2.1, 2.4, 2.2, 2.7, 3.0, 2.6, 2.3, 2.8, 3.5, 2.9, 2.5],
    months: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    newsKeywords: ["gas production pakistan", "PPL exploration", "energy circular debt", "oil gas exploration"],
  },
  HBL: {
    name: "Habib Bank Limited",
    sector: "Banking",
    price: 335,
    prevClose: 330,
    weekHigh52: 369.99,
    weekLow52: 168,
    pe: 7.2,
    marketCap: "500B",
    volume: "3.5M",
    analystRating: "Buy",
    analystCount: 5,
    targetPrice: 415,
    dividendYield: 9.31,
    beta: 1.10,
    eps: 46.5,
    roe: 20.1,
    debtToEquity: 0,
    shariah: false,
    description: "Pakistan's largest bank by assets — 1,700+ branches",
    catalysts: ["9.31% dividend yield", "Largest bank by assets/deposits", "International network"],
    risks: ["Rate cut margin compression", "Regulatory compliance costs", "Q3 income slightly down"],
    priceHistory: [168, 190, 215, 235, 260, 280, 300, 315, 330, 370, 350, 335],
    volumeHistory: [2.5, 2.9, 3.3, 3.1, 3.7, 4.0, 3.6, 3.2, 3.8, 4.5, 3.9, 3.5],
    months: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    newsKeywords: ["HBL earnings", "habib bank", "pakistan banking", "HBL dividend"],
  },
  MCB: {
    name: "MCB Bank",
    sector: "Banking",
    price: 414,
    prevClose: 410,
    weekHigh52: 452,
    weekLow52: 247,
    pe: 9.03,
    marketCap: "490B",
    volume: "2.2M",
    analystRating: "Buy",
    analystCount: 4,
    targetPrice: 515,
    dividendYield: 4.5,
    beta: 0.95,
    eps: 45.8,
    roe: 25.3,
    debtToEquity: 0,
    shariah: false,
    description: "Highest ROE in banking, legendary dividend consistency",
    catalysts: ["Highest ROE in sector", "Defensive beta (0.95)", "Digital banking acceleration"],
    risks: ["Higher P/E than UBL/HBL", "NIM sensitivity to rate cuts", "Down from 52-week high"],
    priceHistory: [247, 270, 295, 310, 330, 350, 370, 385, 400, 452, 430, 414],
    volumeHistory: [1.6, 1.9, 2.2, 2.0, 2.4, 2.7, 2.3, 2.0, 2.5, 3.2, 2.6, 2.2],
    months: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    newsKeywords: ["MCB bank", "mcb earnings", "banking sector psx", "digital banking pakistan"],
  },
  // === Additional stocks from portfolio ===
  ENGROH: {
    name: "Engro Holdings",
    sector: "Conglomerate",
    price: 268,
    prevClose: 263,
    weekHigh52: 295,
    weekLow52: 145,
    pe: 10.2,
    marketCap: "155B",
    volume: "1.2M",
    analystRating: "Buy",
    analystCount: 3,
    targetPrice: 340,
    dividendYield: 3.8,
    beta: 1.10,
    eps: 26.3,
    roe: 15.8,
    debtToEquity: 0.6,
    shariah: false,
    description: "Diversified conglomerate — fertilizer, energy, petrochemicals, telecom",
    catalysts: ["Diversified revenue streams", "Engro Fertilizer dividend flow", "Petrochemical expansion"],
    risks: ["Holding company discount", "Subsidiary performance dependency", "Regulatory risks"],
    priceHistory: [145, 160, 175, 190, 210, 225, 240, 255, 270, 295, 280, 268],
    volumeHistory: [0.8, 1.0, 1.2, 1.1, 1.3, 1.5, 1.4, 1.1, 1.3, 1.8, 1.5, 1.2],
    months: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    newsKeywords: ["engro holdings", "engro fertilizer", "engro polymer", "conglomerate psx"],
  },
  MARI: {
    name: "Mari Petroleum",
    sector: "Energy",
    price: 605,
    prevClose: 599,
    weekHigh52: 650,
    weekLow52: 350,
    pe: 6.8,
    marketCap: "202B",
    volume: "0.8M",
    analystRating: "Buy",
    analystCount: 4,
    targetPrice: 750,
    dividendYield: 5.5,
    beta: 1.20,
    eps: 88.9,
    roe: 28.5,
    debtToEquity: 0.1,
    shariah: true,
    description: "Gas exploration & production — Pakistan's 3rd largest gas producer",
    catalysts: ["High ROE (28.5%)", "Low debt, strong cash generation", "Gas price revisions"],
    risks: ["Single-field concentration risk", "Govt pricing controls", "Depletion risk"],
    priceHistory: [350, 380, 410, 440, 470, 500, 530, 560, 590, 650, 620, 605],
    volumeHistory: [0.5, 0.6, 0.7, 0.7, 0.8, 0.9, 0.8, 0.7, 0.8, 1.1, 0.9, 0.8],
    months: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    newsKeywords: ["mari petroleum", "gas exploration", "gas production pakistan", "MARI earnings"],
  },
  OGDC: {
    name: "OGDC",
    sector: "Energy",
    price: 268,
    prevClose: 264,
    weekHigh52: 290,
    weekLow52: 120,
    pe: 5.5,
    marketCap: "1.15T",
    volume: "5.0M",
    analystRating: "Buy",
    analystCount: 5,
    targetPrice: 350,
    dividendYield: 6.2,
    beta: 1.30,
    eps: 48.7,
    roe: 16.5,
    debtToEquity: 0.1,
    shariah: true,
    description: "Pakistan's largest E&P company — dominant gas and oil producer",
    catalysts: ["Lowest P/E in E&P sector", "6.2% dividend yield", "New exploration blocks"],
    risks: ["Circular debt exposure", "Depleting mature fields", "Govt receivables"],
    priceHistory: [120, 140, 155, 170, 185, 200, 220, 240, 260, 290, 275, 268],
    volumeHistory: [3.0, 3.5, 4.0, 3.8, 4.5, 5.0, 4.5, 4.0, 4.8, 6.0, 5.5, 5.0],
    months: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    newsKeywords: ["OGDC", "oil gas development", "exploration production", "energy sector psx"],
  },
  PAEL: {
    name: "Pak Elektron",
    sector: "Electronics",
    price: 36,
    prevClose: 35.50,
    weekHigh52: 42,
    weekLow52: 18,
    pe: 14.5,
    marketCap: "28B",
    volume: "8.0M",
    analystRating: "Hold",
    analystCount: 2,
    targetPrice: 45,
    dividendYield: 1.2,
    beta: 1.35,
    eps: 2.48,
    roe: 12.0,
    debtToEquity: 0.8,
    shariah: true,
    description: "Consumer electronics & electrical equipment — PEL brand",
    catalysts: ["Consumer recovery play", "Market leader in appliances", "Rate cuts boost consumer credit"],
    risks: ["High beta / speculative", "Thin margins", "Import dependency for components"],
    priceHistory: [18, 20, 22, 24, 27, 29, 31, 33, 36, 42, 38, 36],
    volumeHistory: [5.0, 6.0, 7.0, 6.5, 7.5, 8.5, 8.0, 7.0, 8.0, 10.0, 9.0, 8.0],
    months: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    newsKeywords: ["pak elektron", "PEL", "consumer electronics", "appliances pakistan"],
  },
  SNGP: {
    name: "Sui Northern Gas",
    sector: "Utilities",
    price: 92,
    prevClose: 91,
    weekHigh52: 110,
    weekLow52: 42,
    pe: 8.5,
    marketCap: "55B",
    volume: "3.5M",
    analystRating: "Hold",
    analystCount: 3,
    targetPrice: 120,
    dividendYield: 2.0,
    beta: 1.25,
    eps: 10.8,
    roe: 11.5,
    debtToEquity: 2.5,
    shariah: false,
    description: "Gas utility — distributes natural gas in northern Pakistan",
    catalysts: ["Tariff revisions expected", "Monopoly in distribution", "Govt infrastructure support"],
    risks: ["High debt levels", "Circular debt exposure", "Gas supply constraints", "UFG losses"],
    priceHistory: [42, 48, 55, 60, 65, 72, 78, 84, 90, 110, 98, 92],
    volumeHistory: [2.0, 2.5, 3.0, 2.8, 3.2, 3.8, 3.5, 3.0, 3.5, 4.5, 4.0, 3.5],
    months: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    newsKeywords: ["sui northern gas", "SNGP", "gas utility", "gas tariff pakistan"],
  },
  MZNPETF: {
    name: "Meezan Pakistan ETF",
    sector: "ETF",
    price: 18.50,
    prevClose: 18.22,
    weekHigh52: 20.50,
    weekLow52: 10,
    pe: 0,
    marketCap: "5B",
    volume: "15M",
    analystRating: "Buy",
    analystCount: 0,
    targetPrice: 22,
    dividendYield: 2.5,
    beta: 0.95,
    eps: 0,
    roe: 0,
    debtToEquity: 0,
    shariah: true,
    description: "Shariah-compliant ETF tracking Meezan Pakistan Index — diversified market exposure",
    catalysts: ["Broad market exposure in one instrument", "Shariah compliant", "Low cost diversification"],
    risks: ["Tracks overall market — no alpha", "Liquidity can be thin", "NAV discount/premium"],
    priceHistory: [10, 11, 12, 13, 14, 15, 16, 17, 18, 20.5, 19, 18.5],
    volumeHistory: [8, 10, 12, 11, 13, 15, 14, 12, 14, 18, 16, 15],
    months: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    newsKeywords: ["meezan etf", "pakistan etf", "index fund psx", "shariah etf"],
  },
};

export const KSE100_DATA = [
  { month: "Apr", value: 72000 }, { month: "May", value: 75500 }, { month: "Jun", value: 78000 },
  { month: "Jul", value: 82000 }, { month: "Aug", value: 88000 }, { month: "Sep", value: 95000 },
  { month: "Oct", value: 105000 }, { month: "Nov", value: 118000 }, { month: "Dec", value: 135000 },
  { month: "Jan", value: 170000 }, { month: "Feb", value: 162000 }, { month: "Mar", value: 154292 },
];

export const SECTOR_DATA = [
  { sector: "Banking", weight: 38, return1y: 85 },
  { sector: "Energy", weight: 18, return1y: 55 },
  { sector: "Cement", weight: 12, return1y: 42 },
  { sector: "Technology", weight: 8, return1y: 65 },
  { sector: "Fertilizer", weight: 7, return1y: 30 },
  { sector: "Other", weight: 17, return1y: 25 },
];

export const MACRO_FACTORS = [
  {
    id: "oil",
    name: "Oil Price Crisis",
    status: "high_risk",
    impact: "negative",
    affectedTickers: ["PSO", "PPL"],
    description: "Brent crude above $85 due to Iran conflict. Strait of Hormuz disruptions threaten supply chains. Direct impact on energy sector margins and Pakistan's import bill.",
    lastUpdated: "2026-03-19",
  },
  {
    id: "rates",
    name: "SBP Rate Cut Cycle",
    status: "positive",
    impact: "positive",
    affectedTickers: ["UBL", "HBL", "MCB", "MEBL", "LUCK"],
    description: "Policy rate at 10.5% after 50bps cut. Lower rates boost equities but compress bank NIMs. Net positive for market sentiment.",
    lastUpdated: "2026-03-19",
  },
  {
    id: "imf",
    name: "IMF Program Stability",
    status: "stable",
    impact: "positive",
    affectedTickers: ["PSO", "UBL", "HBL", "MCB", "MEBL"],
    description: "~$7B extended fund facility intact. Circular debt resolution on agenda. Forex reserves doubled from crisis levels.",
    lastUpdated: "2026-03-19",
  },
  {
    id: "mideast",
    name: "Middle East Conflict",
    status: "high_risk",
    impact: "mixed",
    affectedTickers: ["PSO", "PPL", "UBL"],
    description: "Iran war escalation affects energy markets globally. UBL has Middle East exposure. Oil price volatility creates uncertainty for Pakistan's current account.",
    lastUpdated: "2026-03-19",
  },
  {
    id: "pkr",
    name: "PKR/USD Exchange Rate",
    status: "moderate_risk",
    impact: "mixed",
    affectedTickers: ["SYS", "PSO", "LUCK"],
    description: "Rupee under pressure from global risk-off sentiment. SYS benefits from weaker PKR (USD revenues). Importers like PSO face higher costs.",
    lastUpdated: "2026-03-19",
  },
  {
    id: "monsoon",
    name: "Climate / Monsoon Risk",
    status: "watching",
    impact: "negative",
    affectedTickers: ["LUCK", "PPL"],
    description: "NDMA warns 2026 monsoon up to 26% wetter. Risk of floods disrupting infrastructure projects and energy supply chains.",
    lastUpdated: "2026-03-19",
  },
];

export function computeScore(stock) {
  let score = 50;
  if (stock.pe < 7) score += 15;
  else if (stock.pe < 10) score += 10;
  else if (stock.pe < 15) score += 5;
  else score -= 5;
  const upside = ((stock.targetPrice - stock.price) / stock.price) * 100;
  if (upside > 30) score += 15;
  else if (upside > 20) score += 10;
  else if (upside > 10) score += 5;
  if (stock.analystRating === "Strong Buy") score += 10;
  else if (stock.analystRating === "Buy") score += 5;
  if (stock.dividendYield > 5) score += 10;
  else if (stock.dividendYield > 3) score += 5;
  if (stock.roe > 20) score += 5;
  if (stock.beta < 1) score += 5;
  else if (stock.beta > 1.3) score -= 5;
  return Math.min(100, Math.max(0, score));
}
